# Generated by Django 5.2.4 on 2025-11-09 07:32

import myhealthplans.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('policy_name', models.CharField(max_length=255)),
                ('policy_type', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('policy_number', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sum_assured', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aadhar', models.FileField(blank=True, null=True, storage=myhealthplans.storages_backends.R2PublicStorage(), upload_to='documents/aadhar/')),
                ('pan', models.FileField(blank=True, null=True, storage=myhealthplans.storages_backends.R2PublicStorage(), upload_to='documents/pan/')),
                ('document', models.FileField(blank=True, null=True, storage=myhealthplans.storages_backends.R2PublicStorage(), upload_to='documents/policies/')),
                ('aadhar_public_url', models.URLField(blank=True, null=True)),
                ('pan_public_url', models.URLField(blank=True, null=True)),
                ('document_public_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
