# Generated by Django 5.2.4 on 2025-11-09 07:53

import myhealthplans.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='aadhar_public_url',
            new_name='banner_image_public_url',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='document',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='document_public_url',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='pan',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='pan_public_url',
        ),
        migrations.AddField(
            model_name='policy',
            name='banner_image',
            field=models.FileField(blank=True, null=True, storage=myhealthplans.storages_backends.R2PublicStorage(), upload_to='itinerary/banner'),
        ),
    ]
