# Generated by Django 5.2.4 on 2025-11-09 07:58

import myhealthplans.storages_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_rename_aadhar_public_url_policy_banner_image_public_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='banner_image_public_url',
            new_name='aadhar_public_url',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='banner_image',
        ),
        migrations.AddField(
            model_name='policy',
            name='aadhar',
            field=models.FileField(blank=True, null=True, storage=myhealthplans.storages_backends.R2PublicStorage(), upload_to='documents/aadhar/'),
        ),
        migrations.AddField(
            model_name='policy',
            name='document',
            field=models.FileField(blank=True, null=True, storage=myhealthplans.storages_backends.R2PublicStorage(), upload_to='documents/policies/'),
        ),
        migrations.AddField(
            model_name='policy',
            name='document_public_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='pan',
            field=models.FileField(blank=True, null=True, storage=myhealthplans.storages_backends.R2PublicStorage(), upload_to='documents/pan/'),
        ),
        migrations.AddField(
            model_name='policy',
            name='pan_public_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
