# Generated by Django 5.2.4 on 2025-11-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_rename_banner_image_public_url_policy_aadhar_public_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
